version: '3.8'

services:
  sso-db:
    image: postgres:11.4
    container_name: sso-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.bin/db-setup.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    network_mode: host

  sso-portal-ui:
    container_name: sso-portal-ui
    image: sso-requests:latest
    entrypoint: yarn
    command: ['--cwd', './app', 'dev']
    environment:
      - APP_ENV=develop
      - API_URL=/app
      - SSO_URL=https://dev.oidc.gov.bc.ca/auth/realms/onestopauth
      - SSO_CLIENT_ID=sso-requests
      - SSO_REDIRECT_URI=http://localhost:3000
      - SSO_AUTHORIZATION_RESPONSE_TYPE=code
      - SSO_AUTHORIZATION_SCOPE=openid
      - SSO_TOKEN_GRANT_TYPE=authorization_code
      - KC_IDP_HINT=idir
      - ENABLE_GOLD=false=value
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - sso-requests
    network_mode: host
    volumes:
      - ./app:/app/app
      - app-node-modules:/app/app/node_modules/

  sso-requests:
    container_name: sso-requests
    image: sso-requests:latest
    entrypoint: ['/bin/bash', '-c', 'yarn --cwd ./localserver migrate-db && yarn --cwd ./localserver dev']
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ssorequests
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sso-db
    network_mode: host
    volumes:
      - ./lambda:/app/lambda
      - /app/lambda/node_modules/
      - ./lambda/shared:/app/lambda/shared
      - /app/lambda/shared/node_modules/
      - ./lambda/app:/app/lambda/app
      - /app/lambda/app/node_modules/
      - ./lambda/actions:/app/lambda/actions
      - /app/lambda/actions/node_modules/
      - ./lambda/db:/app/lambda/db
      - /app/lambda/db/node_modules/
      - ./lambda/scheduler:/app/lambda/scheduler
      - /app/lambda/scheduler/node_modules/
      - ./localserver:/app/localserver
      - /app/localserver/node_modules/
      - ./app:/app/app
      - app-node-modules:/app/app/node_modules/

volumes:
  app-node-modules:
