name: Build and Deploy GH Pages

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '.github/**'
      - 'app/**'

env:
  SSO_CLIENT_ID: sso-requests
  DEPLOY_REPO_BRANCH: gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Set env to development
        if: endsWith(github.ref, '/dev')
        run: |
          cat >> $GITHUB_ENV <<EOF
          APP_ENV=develop
          APP_URL=https://bcgov.github.io/sso-terraform-dev
          APP_BASE_PATH=/sso-terraform-dev
          API_URL=https://gcp9dahm4c.execute-api.ca-central-1.amazonaws.com/test/app/
          SSO_URL=https://dev.oidc.gov.bc.ca/auth/realms/onestopauth
          DEPLOY_REPO_NAME=bcgov/sso-terraform-dev
          EOF
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
          cat >> $GITHUB_ENV <<EOF
          APP_ENV=production
          APP_URL=https://bcgov.github.io/sso-requests
          APP_BASE_PATH=/sso-requests
          API_URL=https://kgodz1zmk2.execute-api.ca-central-1.amazonaws.com/test/app/
          SSO_URL=https://oidc.gov.bc.ca/auth/realms/onestopauth
          DEPLOY_REPO_NAME=bcgov/sso-requests
          EOF
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        env:
          APP_ENV: ${{ env.APP_ENV }}
          APP_URL: ${{ env.APP_URL }}
          APP_BASE_PATH: ${{ env.APP_BASE_PATH }}
          API_URL: ${{ env.API_URL }}
          SSO_URL: ${{ env.SSO_URL }}
          SSO_CLIENT_ID: ${{ env.SSO_CLIENT_ID }}
          KC_IDP_HINT: idir
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository-name: ${{ env.DEPLOY_REPO_NAME }}
          branch: ${{ env.DEPLOY_REPO_BRANCH }}
          folder: ./app/out
