name: Build and Deploy
on:
  push:
    branches: [dev]

# it will use workflow_run event once it got merged into the main branch
# on:
#   workflow_run:
#     workflows: ['Run Tests and Lints']
#     branches: [dev]
#     types:
#       - completed
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        env:
          API_URL: ${{ secrets.API_URL }}
          SSO_URL: ${{ secrets.SSO_URL }}
          SSO_CLIENT_ID: ${{ secrets.SSO_CLIENT_ID }}
          SSO_REDIRECT_URI: ${{ secrets.SSO_REDIRECT_URI }}
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./app/out
