name: Build and Deploy in Prod

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        env:
          APP_URL: ${{ secrets.PROD_APP_URL }}
          APP_BASE_PATH: ${{ secrets.PROD_APP_BASE_PATH }}
          API_URL: ${{ secrets.API_URL }}
          SSO_URL: ${{ secrets.SSO_URL }}
          SSO_CLIENT_ID: ${{ secrets.SSO_CLIENT_ID }}
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./app/out
