name: OWASP ZAP Scan

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:3000
      - name: ZAP Scan App
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:3000'
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: ZAP Scan API
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080/api/v1'
          token: ${{ secrets.GITHUB_TOKEN}}
